
-- ops.app.pa.busobj.auth.users_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:30--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_USERS;

CREATE TABLE TPA_USERS (
	ID INT8 NOT NULL,
	NAME VARCHAR(20) NULL,
	CREATED_DATE DATE NOT NULL
);

-- ops.app.pa.busobj.docsystem.document_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:30--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_DOCUMENT;

CREATE TABLE TPA_DOCUMENT (
	IDENT VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NULL,
	CREATED_DATE DATE NOT NULL,
	STATUS OID,
	FORMAT OID,
	TYPE OID
);

-- ops.app.pa.busobj.docsystem.folder_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:30--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_FOLDER;

CREATE TABLE TPA_FOLDER (
	IDENT VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NULL,
	CREATED_DATE DATE NOT NULL,
	MODIFIED_DATE DATE NOT NULL,
	LOCATION VARCHAR(20) NOT NULL,
	SUBFOLDERS OID,
	DOCUMENTS OID
);

-- ops.app.pa.busobj.projmgt.batches_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:30--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_BATCHES;

CREATE TABLE TPA_BATCHES (
	ID INT8 NOT NULL,
	NAME VARCHAR(40) NULL,
	DESCRIPTION VARCHAR(80) NULL,
	ESTIMATED_START_DATE DATE NOT NULL,
	ESTIMATED_END_DATE DATE NOT NULL,
	ACTUAL_START_DATE DATE NOT NULL,
	ACTUAL_END_DATE DATE NOT NULL,
	DURATION INTERVAL NULL,
	COST1 NUMERIC(8,2) NULL,
	COST2 NUMERIC(8,2) NULL,
	REQUIREMENTS OID,
	FOLDERS_ OID,
	DOCUMENTS OID,
	KEYWORDS OID,
	PRIORITY NUMERIC(8,2) NULL,
	RELATED_RELEASE NUMERIC(8,2) NULL
);

-- ops.app.pa.busobj.projmgt.project_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:30--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_PROJECT;

CREATE TABLE TPA_PROJECT (
	ID INT8 NOT NULL,
	IDENT VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NULL,
	CREATED_DATE DATE NOT NULL,
	MODIFIED_DATE DATE NOT NULL,
	DATATYPE OID,
	STATUS OID,
	DOCUMENTS OID,
	FOLDERS OID
);

-- ops.app.pa.busobj.projmgt.teams_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:31--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_TEAMS;

CREATE TABLE TPA_TEAMS (
	ID INT8 NOT NULL,
	NAME VARCHAR(40) NULL,
	DESCRIPTION VARCHAR(80) NULL,
	LEADER OID,
	PERSONS OID,
	SPEC_SKILLS OID
);

-- ops.app.pa.busobj.projmgt.persons_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:31--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_PERSONS;

CREATE TABLE TPA_PERSONS (
	ID INT8 NOT NULL,
	NAME VARCHAR(40) NULL,
	FIRSTNAME VARCHAR(40) NULL,
	OFFICE_PHONE1 VARCHAR(16) NULL,
	OFFICE_PHONE2 VARCHAR(16) NULL,
	HOME_PHONE VARCHAR(16) NULL,
	MOBILE_PHONE VARCHAR(16) NULL,
	EMAIL1 VARCHAR(40) NULL,
	EMAIL2 VARCHAR(40) NULL,
	SKILLS OID
);

-- ops.app.pa.busobj.projmgt.skills_create.sql - Copyright (C) Pascal Munerot 2001.
-- This file belongs to the 'Project Architect' project and is licensed under the GNU Public License.
-- Generated by generate.pl at 15/3/2002 21:6:31--
-- DO NOT EDIT THIS FILE. ANY CHANGE WILL BE LOST UPON THE NEXT CODE GENERATION
--








 

DROP TABLE TPA_SKILLS;

CREATE TABLE TPA_SKILLS (
	ID INT8 NOT NULL,
	DESCRIPTION VARCHAR(40) NULL,
	SKILLDATATYPE OID,
	SKILLLEVEL OID,
	COMMENT TEXT NULL
);
